---
output: 
  github_document:
    html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
<!-- badges: start -->
<!-- badges: end -->

# stanfordnlp

Stanford NLP in R.

## Installation

``` r
# install.packages("remotes")
remotes::install_github("news-r/stanfordnlp")
```

## Example

Reproduction of [quick example](https://stanfordnlp.github.io/stanfordnlp/installation_usage.html)

```{r, eval=FALSE}
library(stanfordnlp)

download_model(lang = "en")
pipeline <- create_pipeline()
doc <- pipeline("Barack Obama was born in Hawaii. He was elected president in 2008.")
doc$sentences[[1]]$print_dependencies()
```

```{r, echo=FALSE}
library(stanfordnlp)

reticulate::use_virtualenv("./env")

# Quick Example from site
# https://stanfordnlp.github.io/stanfordnlp/installation_usage.html
pipeline <- create_pipeline(models_dir = "model")
doc <- pipeline("Barack Obama was born in Hawaii. He was elected president in 2008.")
cat(reticulate::py_capture_output(doc$sentences[[1]]$print_dependencies()))
```
